services:
  core:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "8080:8080"
    deploy:
      replicas: 1
    restart: unless-stopped
    depends_on:
      db:
        condition: service_started
    environment:
      - ACTIVE_PROFILE=dev
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/${DB_DATABASE}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - SPRING_DATASOURCE_USERNAME=${DB_USERNAME}
    volumes:
      - maven-cache:/root/.m2

  db:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    restart: unless-stopped
    environment:
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - db_volume:/var/lib/postgresql/data


volumes:
  db_volume:
  maven-cache: